### ISSUE TITLE
Release 1.2 crashes on clicking "connect"

### ISSUE THREAD

**Issue by steppe** [Nauplius/PeoplePickerPortTester#1] opened 2015-02-17 09:08 UTC
System:
W2kR12 - latest patches
Sharepoint 2013 SP1

Eventlog:
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: peoplepicker port tester.exe
P2: 1.0.0.0
P3: 54d84550
P4: mscorlib
P5: 2.0.0.0
P6: 53a120d7
P7: 20cf
P8: 100
P9: N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
P10: 

Attached files:

These files may be available here:
C:\Users\spuser\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_peoplepicker por_4b705e1755e3715db197ec9f63aad8d77a7cd47f_00000000_dc1d28d6

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4634c4bf-b684-11e4-80de-00155d28d60e
Report Status: 2048
Hashed bucket:

**Comment by tseward** [comment] 2015-02-17 15:12
Thanks for the report. I can't reproduce it, however, and this isn't enough information to identify a potential cause and fix, unfortunately.

Are you running the application from a network share, or has the exe been copied locally to the 2012 R2 server?

**Comment by tseward** [comment] 2015-02-17 23:38
I've identified the issue and it should be resolved in the next release.

**Closed** 2015-02-18 00:23 UTC
Labels: bug
